In [3]:
import numpy as np

In [8]:
a1 = np.arange(1,6)
a2 = np.arange(7,12)
print(a1)
print(a2)

[1 2 3 4 5]
[ 7  8  9 10 11]


In [9]:
a1 + a2

array([ 8, 10, 12, 14, 16])

In [10]:
a1 - a2

array([-6, -6, -6, -6, -6])

In [11]:
a1 * a2

array([ 7, 16, 27, 40, 55])

In [12]:
a1 / a2

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545])

In [13]:
a1 // a2

array([0, 0, 0, 0, 0])

In [14]:
a1 ** a2

array([       1,      256,    19683,  1048576, 48828125])

In [16]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [20]:
arr + 10 #it's broadcasting which adds single element to every element of array
# it's valid in matrix too

array([20, 30, 40, 50])

In [21]:
# we copy array a in b and perform operations on b then it affects the array a too which is deep copy
a =  np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
b = a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
b[0] = 10000

In [24]:
a

array([10000,     2,     3,     4,     5,     6,     7,     8,     9,
          10,    11,    12,    13,    14,    15,    16,    17,    18,
          19,    20])

In [25]:
# we take a slice of a and store it in slice_a array and perform operations on sliced array 
#then changes will not reflect in array a which is called as shalow copy
sliced_array = a[0:6]
sliced_array

array([10000,     2,     3,     4,     5,     6])

In [28]:
sliced_array = sliced_array * 2
sliced_array

array([40000,     8,    12,    16,    20,    24])

In [29]:
a

array([10000,     2,     3,     4,     5,     6,     7,     8,     9,
          10,    11,    12,    13,    14,    15,    16,    17,    18,
          19,    20])

In [31]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(5,9).reshape(2,2)

In [32]:
A

array([[1, 2],
       [3, 4]])

In [33]:
B

array([[5, 6],
       [7, 8]])

In [37]:
A @ B # @ is used for Multiplication 

array([[19, 22],
       [43, 50]])

In [39]:
np.dot(A,B) # it is also doing multiplication

array([[19, 22],
       [43, 50]])

In [40]:
A.T #Giving Result in Transpose

array([[1, 3],
       [2, 4]])

In [41]:
a = np.arange(1,6)
b = np.arange(6,11)


In [43]:
np.vstack((a,b)) #Vertically Stacking vectors ....Matrix stacking is not Available

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#Split in columns use hsplit
np.hsplit(arr,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [8]:
#split in rows use vsplit
np.vsplit(arr,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]