In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6]

17

In [4]:
arr[-4]

17

In [10]:
arr[0:7] #start point -->> endpoint+1
# startpoint : endpoint 
# startpoint -->> blank --->>> from 0th index
#endpoint -->> blank --->>> till end 

array([11, 12, 13, 14, 15, 16, 17])

In [11]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
#arr[start : end : step]
arr[2::2]

array([13, 15, 17, 19])

In [18]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[1] # single argument means row

array([ 6,  7,  8,  9, 10])

In [17]:
arr[0,0] #2 arguments seperated by comma means specific element

1

In [20]:
arr[0:3,1:4] #slice matrix under a matrix

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [22]:
arr[3:,3:] #same here blank is end ....slicing matrix under matrix

array([[19, 20],
       [24, 25],
       [29, 30]])

In [24]:
arr[:,2] #for printing a particular column 

array([ 3,  8, 13, 18, 23, 28])

**printing even and Odd integers**

In [29]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
bool_index = arr%2 != 0 # ==0 is for even and != 0  is for odd
bool_index

array([ True,  True,  True,  True,  True])

In [31]:
arr = arr[bool_index]
arr

array([11, 13, 15, 17, 19])