Valid Sudoku

In [2]:
import numpy as np

In [3]:
s = np.random.randint(1,10,81).reshape(9,9)
s

array([[2, 7, 2, 6, 9, 7, 8, 3, 7],
       [5, 9, 5, 6, 7, 5, 7, 6, 1],
       [9, 5, 9, 9, 3, 7, 1, 5, 1],
       [7, 5, 1, 2, 5, 9, 2, 7, 1],
       [1, 1, 5, 8, 2, 7, 5, 7, 1],
       [5, 4, 8, 5, 4, 3, 4, 8, 7],
       [9, 1, 8, 4, 9, 9, 5, 7, 3],
       [7, 7, 5, 5, 9, 1, 3, 9, 7],
       [6, 2, 8, 2, 3, 5, 3, 7, 2]])

In [4]:
b = np.sum(s,axis=1)
for i in b:
    if i != 45:
        print("Sudoku is Not valid for rows")
        break
else:
    print("Sudoku is valid for rows")

Sudoku is Not valid for rows


In [5]:
c = np.sum(s,axis=0)
for i in c:
    if i != 45:
        print("Sudoku is Not valid for columns")
        break
else:
    print("Sudoku is valid for rows")

Sudoku is Not valid for columns


In [6]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        sum = n.sum()
        if sum != 45:
            print("Invalid Sudoku")
            break
    else:
        print("valid")

Invalid Sudoku
Invalid Sudoku
Invalid Sudoku


In [42]:
# columns : [Age , Math MArks , Science Marks]

data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [8]:
#Get the Shapte of the matrix
data.shape

(5, 3)

In [9]:
#find the avg age of students
a = np.average(data,axis=0)
print(a[0])

18.4


In [10]:
##### Extract math marks of all students
m = data[0:5,1:2]
m

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [11]:
#find highest science marks
s = data[:5,2:]
print(max(s))

[95]


In [12]:
#get details of the student who scored more than 90 in math
data[data[:,1] > 90]

array([[19, 92, 88]])

In [15]:
#increase math marks of all students by 5
math = data[:,1:2]
math = math + 5
math

array([[90],
       [97],
       [81],
       [70],
       [95]])

In [26]:
#find how many students are younger than 19

ar = data[data[:,0] < 19]
len(ar)

3

In [27]:
#calculate average marks for each subject
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [37]:
#get data of students who scored at least 80 in both subjects
ar = data[:,1:]
ag = ar[ar >= 80]
ag
# data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([85, 92, 88, 95, 90, 85])

In [41]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])

In [43]:
#replace all science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0 
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])