In [1]:
import numpy as np


In [2]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [3]:
arr = np.array(l)
arr

array([1, 2, 3, 4])

In [4]:
list = [1,2,3.5,'Revati']

In [8]:
array = np.array(list)
array
#convert everything to string instead of throwing error

array(['1', '2', '3.5', 'Revati'], dtype='<U32')

In [9]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [13]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arr = np.ones(8)
arr

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
arr = np.linspace(1,10,5)
arr
#linear spacing

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
#Random library generates between 0 to 1 which is normalization
arr = np.random.randint(1,10,5)
arr

array([8, 7, 6, 2, 7])

In [21]:
np.random.rand(5)

array([0.91062832, 0.52245316, 0.67693442, 0.70864175, 0.15264399])

In [25]:
# random.randn() generates between -3 to 3 which is standardization
np.random.randn(5)

array([ 0.12501163,  0.88609422,  2.1346573 ,  0.73981787, -1.09106398])

In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.shape

(3, 3)

In [30]:
arr.size

9

In [31]:
arr.dtype

dtype('int32')

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.sum()

45

In [39]:
np.sum(arr,axis=0) #0 is for column

array([12, 15, 18])

In [40]:
np.sum(arr,axis=1) #1 is for row

array([ 6, 15, 24])

In [41]:
arr.min()

1

In [42]:
arr.max()

9

In [43]:
arr.mean()

5.0

In [44]:
arr.std()

2.581988897471611

In [46]:
arr.argmax() #argmax is for index of max element

8

In [47]:
arr.argmin() #argmin is for index of min element

0

In [50]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
arr = arr.reshape(6,5) #reshaping any array in given dimension 
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])